### ISSUE TITLE
Later milestone should not overwrite the previous milestone's feature completely

### ISSUE THREAD

**Issue by noRubidium** [teaching-js/assignment#2]
For higher milestones, it should not override the feature in the lower milestones.

For example:
Milestone 2: Pagination
Milestone 3: Infinite scroll

Instead of making milestone 3 to be replacing milestone 2, it might be better to let the students build an option in user to set preference of a given user's display to be either pagination or infinite scroll.

**Comment by DarkPurple141** [comment]
@noRubidium Open to changes if you make a PR.

-- Minje I don't have much time (I'm at work now) to overhaul large parts of codebase. If you want to jump in and improve aspects I've given you the ability to do so for this very reason.

Basically just me and Zain putting in bits and pieces where we can.
